/**
 * Orin.LAB · Setup Wizard
 * Interactive first-time setup — saves config to ~/.orinlab/.env
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import * as readline from "readline";

const CONFIG_DIR = join(homedir(), ".orinlab");
const CONFIG_FILE = join(CONFIG_DIR, ".env");

const BANNER = `
 ██████╗ ██████╗ ██╗███╗   ██╗   ██╗      █████╗ ██████╗
██╔═══██╗██╔══██╗██║████╗  ██║   ██║     ██╔══██╗██╔══██╗
██║   ██║██████╔╝██║██╔██╗ ██║   ██║     ███████║██████╔╝
██║   ██║██╔══██╗██║██║╚██╗██║   ██║     ██╔══██║██╔══██╗
╚██████╔╝██║  ██║██║██║ ╚████║   ███████╗██║  ██║██████╔╝
 ╚═════╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝   ╚══════╝╚═╝  ╚═╝╚═════╝

AI Research Lab for Crypto Markets · Built on Solana
`;

function mask(value: string): string {
  if (!value || value.length < 8) return "••••••••";
  return value.slice(0, 4) + "••••" + value.slice(-4);
}

function loadExisting(): Record<string, string> {
  const existing: Record<string, string> = {};
  if (!existsSync(CONFIG_FILE)) return existing;
  for (const line of readFileSync(CONFIG_FILE, "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#") && trimmed.includes("=")) {
      const [k, ...rest] = trimmed.split("=");
      existing[k.trim()] = rest.join("=").trim();
    }
  }
  return existing;
}

function writeEnv(config: Record<string, string>): void {
  mkdirSync(CONFIG_DIR, { recursive: true });
  const lines = [
    "# Orin.LAB — Auto-generated by orinlab setup",
    "# Edit this file to update your config",
    "",
  ];
  for (const [k, v] of Object.entries(config)) {
    if (v) lines.push(`${k}=${v}`);
  }
  writeFileSync(CONFIG_FILE, lines.join("\n"), "utf-8");
}

function createRl(): readline.Interface {
  return readline.createInterface({ input: process.stdin, output: process.stdout });
}

function ask(rl: readline.Interface, question: string, defaultValue = ""): Promise<string> {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

function askYesNo(rl: readline.Interface, question: string, defaultYes = false): Promise<boolean> {
  const hint = defaultYes ? "Y/n" : "y/N";
  return new Promise((resolve) => {
    rl.question(`${question} (${hint}): `, (answer) => {
      const a = answer.trim().toLowerCase();
      if (!a) resolve(defaultYes);
      else resolve(a === "y" || a === "yes");
    });
  });
}

export async function runSetup(): Promise<void> {
  console.log(BANNER);
  console.log(`\nWelcome to Orin.LAB Setup`);
  console.log(`Config will be saved to: ${CONFIG_FILE}\n`);

  const rl = createRl();
  const existing = loadExisting();

  if (Object.keys(existing).length) {
    console.log(`Found existing config at ${CONFIG_FILE}`);
    const update = await askYesNo(rl, "Update existing config?", false);
    if (!update) {
      console.log("\n✓ Using existing config. Run `orinlab bot` to start.\n");
      rl.close();
      return;
    }
  }

  const config: Record<string, string> = { ...existing };

  console.log("\nStep 1 — AI Provider");
  console.log("  1 Anthropic (Claude)");
  console.log("  2 DeepInfra (free tier)");
  const providerChoice = await ask(rl, "Choose provider", "1");

  if (providerChoice === "2") {
    config.AI_PROVIDER = "deepinfra";
    const current = config.DEEPINFRA_API_KEY ?? "";
    const hint = current ? ` (current: ${mask(current)})` : "";
    const key = await ask(rl, `DeepInfra API key${hint}`, current);
    if (key) config.DEEPINFRA_API_KEY = key;
    config.DEEPINFRA_MODEL ??= "meta-llama/Meta-Llama-3.1-70B-Instruct";
    config.DEEPINFRA_VISION_MODEL ??= "meta-llama/Llama-3.2-90B-Vision-Instruct";
  } else {
    config.AI_PROVIDER = "anthropic";
    const current = config.ANTHROPIC_API_KEY ?? "";
    const hint = current ? ` (current: ${mask(current)})` : "";
    const key = await ask(rl, `Anthropic API key${hint}`, current);
    if (key) config.ANTHROPIC_API_KEY = key;
  }

  console.log("\nStep 2 — Telegram Bot");
  console.log("  Get your token from @BotFather on Telegram");
  const tokenCurrent = config.TELEGRAM_BOT_TOKEN ?? "";
  const tokenHint = tokenCurrent ? ` (current: ${mask(tokenCurrent)})` : "";
  const token = await ask(rl, `Telegram bot token${tokenHint}`, tokenCurrent);
  if (token) config.TELEGRAM_BOT_TOKEN = token;

  console.log("\nStep 3 — Solana (optional)");
  if (await askYesNo(rl, "Configure Solana wallet tracking?", false)) {
    config.SOLANA_RPC_URL = await ask(
      rl,
      "Solana RPC URL",
      config.SOLANA_RPC_URL ?? "https://api.mainnet-beta.solana.com",
    );
    const wallet = await ask(rl, "Wallet address to monitor (leave blank to skip)", "");
    if (wallet) config.SOLANA_WALLET_ADDRESS = wallet;
  }

  console.log("\nStep 4 — Twitter/X Auto Poster (optional)");
  if (await askYesNo(rl, "Configure Twitter/X posting?", false)) {
    for (const [keyName, label] of [
      ["TWITTER_API_KEY", "API Key"],
      ["TWITTER_API_SECRET", "API Secret"],
      ["TWITTER_ACCESS_TOKEN", "Access Token"],
      ["TWITTER_ACCESS_SECRET", "Access Secret"],
    ] as const) {
      const current = config[keyName] ?? "";
      const hint = current ? ` (current: ${mask(current)})` : "";
      const val = await ask(rl, `Twitter ${label}${hint}`, current);
      if (val) config[keyName] = val;
    }
    config.AUTO_POST_ENABLED = (await askYesNo(rl, "Enable auto-posting?", false)) ? "true" : "false";
  }

  config.LOG_LEVEL ??= "INFO";
  config.SIGNAL_CONFIDENCE_THRESHOLD ??= "70";
  config.SIGNAL_INTERVAL ??= "300";
  config.AUTO_POST_ENABLED ??= "false";

  writeEnv(config);
  rl.close();

  console.log(`
✓ Setup complete!

Config saved to ${CONFIG_FILE}

Next steps:
  orinlab bot          — start Telegram bot
  orinlab signal       — generate market signals
  orinlab posts SOL    — preview posts
`);
}
